services:
  nginx:
    image: greenpearbear/mynginx_alpine:final
    ports:
      - "8080:8080"
    volumes:
      - type: volume
        source: static-file
        target: /www/html
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  static-file:

